### ISSUE TITLE
REST error(16): Command not allowed

### ISSUE THREAD

**Issue by mathieumd** [Webelys/glpi_ansible#3]
I was just looking for such project. Excellent idea!

While trying it against a GLPI 0.85.4 with Webservices 1.5.0, I can login, but cannot get any further:

``` bash
php glpi_export_hosts.php -g http://glpi/glpi/plugins/webservices/rest.php -u glpi -p p4ssw0rd -d

+ Calling 'glpi.doLogin' on http://glpi/glpi/plugins/webservices/rest.php?login_name=glpi&login_password=p4ssw0rd&method=glpi.doLogin
+ Calling 'glpi.listEntities' on http://glpi/glpi/plugins/webservices/rest.php?session=t3th...9qi0&method=glpi.listEntities
+ Calling 'glpi.listDropdownValues' on http://glpi/glpi/plugins/webservices/rest.php?session=t3th...9qi0&dropdown=domains&method=glpi.listDropdownValues
+ Calling 'glpi.listObjects' on http://glpi/glpi/plugins/webservices/rest.php?session=t3th...9qi0&itemtype=Computer&start=0&limit=20&method=glpi.listObjects
REST error(16): Command not allowed
```

Indeed, the `listObjects` doesn't seems to be allowed:

``` bash
curl 'http://glpi/glpi/plugins/webservices/rest.php?session=t3th...9qi0&itemtype=Computer&start=0&limit=20&method=glpi.listObjects'
{"faultCode":16,"faultString":"Command not allowed"}
```

However, the webservices page in GLPI, tab _Methods_, does list the `glpi.listObjects` (`PluginWebservicesMethodInventaire::methodListObjects`) method as _available_.

The user `glpi` is _Super-Admin_.

What is missing on my setup?

**Comment by camlafit** [comment]
Hi

GLPI with webservices has two account managed : 
- standard glpi account, used to connect to the webgui 
- webservice account to protect URI connection

This script use only standard glpi account , then : 
- your accout must be a normal account with super admin status, is it ?
- in webservices configuration, any account must be set, only an ip restriction

**Comment by mathieumd** [comment]
> your accout must be a normal account with super admin status, is it ?

Yes, it is. But it also has other profiles (Self-Service and Admin), could it be because of this?

> in webservices configuration, any account must be set, only an ip restriction

IP is restricted to my testing PC, and no user or password is configured there, so it should be OK, no?

**Comment by camlafit** [comment]
HI

Looks correct. Can you try with an account having only super admin status ?
In my use case user is super admin and admin.

As problem done also with a curl call, problem come from GLPI
configuration. Now is to find where :)

**Comment by mathieumd** [comment]
The user I was using has 3 authorizations: _Admin_, _Self-Service_ and _Super-Admin_.
I tried removing _Admin_, and left _Self-Service_ and _Super-Admin_: `./glpi.php --list` worked! Add back _Admin_ and it doesn't work anymore. Then I tried to remove _Self-Service_ and left only _Admin_ and _Super-Admin_: it worked too!

Is there a limit in the number of authorizations retrieved?

**Comment by camlafit** [comment]
Hi

Can you try with this patch ?

**Comment by mathieumd** [comment]
It's not better, sorry.
Could you reproduce this bug on your own testing GLPI?

**Comment by camlafit** [comment]
Sorry not, my default profil is always a super admin.

Can you add a var_dump($profile) in L182 , enable debug listing  and paste result ?

**Comment by mathieumd** [comment]
Here is the var_dump when it's working:

```
./glpi.php --list --cache PT0S
array(3) {
  ["id"]=>
  int(3)
  ["name"]=>
  string(5) "Admin"
  ["current"]=>
  int(0)
}
array(3) {
  ["id"]=>
  int(4)
  ["name"]=>
  string(11) "Super-Admin"
  ["current"]=>
  int(1)
}
{"XXX":{"hosts":["xxx","xxx","xxx"],"children":[]}}
```

And here it's when it's failing:

```
./glpi.php --list --cache PT0S
array(3) {
  ["id"]=>
  int(3)
  ["name"]=>
  string(5) "Admin"
  ["current"]=>
  int(0)
}
array(3) {
  ["id"]=>
  int(1)
  ["name"]=>
  string(12) "Self-Service"
  ["current"]=>
  int(1)
}
array(3) {
  ["id"]=>
  int(4)
  ["name"]=>
  string(11) "Super-Admin"
  ["current"]=>
  int(0)
}
REST error(16): Command not allowed
```

**Comment by camlafit** [comment]
Hi

UHUH ok we have some sensitive case . Can you test with L182
    if (strtolower($profile['name']) == 'super-admin' && $profile['current'] != 1) {

**Comment by mathieumd** [comment]
:+1:  It works!! Thank you.

**Comment by camlafit** [comment]
Great news then it's close by 0e0d8910d428fd2c58ea6b763fc8c10aaedf15fd
