### ISSUE TITLE
URL is wrong in version 0.90 and webservice 1.6

### ISSUE THREAD

**Issue by Vaiper** [Webelys/glpi_ansible#6]
Hey,

I want to test this script with the ansible, but the Webservice url have changed:

in your script:

https://cmdb.example.com/glpi/plugins/webservices/rest.php?login_name=USERNAME&login_password=PASSWORD%21&method=glpi.doLogin

in the new Version works for me:

https://cmdb.example.com/glpi/plugins/webservices/rest.php?login_name=USERNAME&login_password=PASSWORD&method=glpi.doLogin

The %21 is to much, I have no idea where this comes...

**Comment by camlafit** [comment]
Hi

Yes looks as an error typo. %21 is an error. I check this.
Thanks

**Comment by camlafit** [comment]
Can you check your ini file ?
Maybe do you have a space on your password line

**Comment by Vaiper** [comment]
no space but an ! in my password. 

Changed the password no i get an permission denied, but when i open the url in the browser, all works fine...

**Comment by camlafit** [comment]
Any new. Is it ok ?

**Comment by Vaiper** [comment]
Looks better, but now i get permission denied 

https://XXXX.XXXXX.de/glpi/plugins/webservices/rest.php?login_name=XXX&login_password=XXX&method=glpi.doLogin

In the glpi I have Super-admin Permissions.

**Comment by camlafit** [comment]
Hi

Ok can you run in debug mode and paste me result ?

`./glpi.php --glpi
https://XXXX.XXXXX.de/glpi/plugins/webservices/rest.php
<https://XXXX.XXXXX.de/glpi/plugins/webservices/rest.php?login_name=XXX&login_password=XXX&method=glpi.doLogin>
--username XXX --password YYY --debug`

Looks as an another problem

**Comment by Vaiper** [comment]
{}[root@XXXXX ansible]# ./glpi -d
- Calling 'glpi.doLogin' on https://XXXX.XXXX.de/glpi/plugins/webservices/rest.php?login_name=XXX&login_password=XXXX&method=glpi.doLogin
  REST error(1): Zugriff verweigert
  {}[root@XXXX ansible]#

**Comment by camlafit** [comment]
Hi

Hum looks a 403.
Can you check your "plugins/webservices/front/client.php" and verify if a
rule allowing your IP is set ?

**Comment by Vaiper** [comment]
![image](https://cloud.githubusercontent.com/assets/474120/14852430/81e5d624-0c86-11e6-93ea-cddcf0a9b472.png)

**Comment by Vaiper** [comment]
Ahhh now it works!

**Comment by camlafit** [comment]
Hi

> picture

Ok may missing ansible group as explained in
https://github.com/Webelys/glpi_ansible#glpi-configuration
​

> Ahhh now it works!

What do you change in your glpi ?

**Comment by Vaiper** [comment]
Yep this was my fault, forget to grant access to the system... 

but now i get this error:

 Calling 'glpi.getObject' on https://XXX.XXXXXXX.de/glpi/plugins/webservices/rest.php?session=47l4etbc36u7r3t5kj4gjerkr7&itemtype=Computer&id=1863&method=glpi.getObject
- Calling 'glpi.getObject' on https://XXX.XXXXXXX.de/glpi/plugins/webservices/rest.php?session=47l4etbc36u7r3t5kj4gjerkr7&itemtype=Computer&id=1864&method=glpi.getObject
- Calling 'glpi.getObject' on https://XXX.XXXXXXX.de/glpi/plugins/webservices/rest.php?session=47l4etbc36u7r3t5kj4gjerkr7&itemtype=Computer&id=1865&method=glpi.getObject
- Calling 'glpi.doLogout' on https://XXXX.XXX.de/glpi/plugins/webservices/rest.php?session=47l4etbc36u7r3t5kj4gjerkr7&method=glpi.doLogout
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287
  PHP Notice:  Undefined index: name in /etc/ansible/glpi_ansible/glpi.php on line 287

**Comment by camlafit** [comment]
Ok then I close this issue and open a new #8
New problem new issue :)

**Comment by camlafit** [comment]
Hi

Can you check #8 ? I can't add you to this new issue as participant. To follow it you must comment 

Thanks
